{% set name = "metoffice-afterburner" %}
{% set version = "1.3.2b2.post1" %}
{% set sha256 = "28b62c97576c53ba3d2070128eed2d7e8e8a44eac5b2fa8709e604f5bd6a0cec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or osx]

requirements:
  host:
    - rsync
    - python
    - pip
  run:
    - python
    - iris >=2.4
    - pyparsing >=2
    - windspharm

test:
  imports:
    - afterburner

about:
  home: https://code.metoffice.gov.uk/trac/afterburner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: Tools and apps for processing numerical climate model data
  description: |
    Afterburner is a Python package that provides functionality for analysing and
    processing climate model data, in particular, though not exclusively, data
    produced by the UK Met Office's Unified Model.
extra:
  recipe-maintainers:
    - ehogan
    - rockdoc
